### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sudan** [sudan/iPersonal#20]
Todo 

- [x] Activity test case
- [x] Activity Dao test case
- [x] Bookmark Service test case
- [x] Bookmark Controller test case
- [x] Todo Service test case
- [x] Todo Controller test case
- [x] Note Service test case
- [x] Note Controller test case
- [x] Auth for google
- [x] Handling session management
- [x] Html separator
- [x] Html aggregator
- [x] Todo create
- [x] Todo Read
- [x] Todo Update
- [x] Todo delete
- [x] Todo count
- [x] Todo paginate
- [x] Todo Dao test case
- [x] Todo service test case
- [x] Todo controller test case
- [x] Diary change data model
- [x] Diary Create
- [x] Diary Read (One page only)
- [x] Diary Update (One page only)
- [x] Diary Delete (One page only)
- [x] Diary Dao test case
- [x] Diary Service test case
- [x] Diary controller test case
- [x] Expense Create
- [x] Expense Read
- [x] Expense Update
- [x] Expense Delete
- [x] Expense count
- [x] Expense paginate
- [x] Expense dao test case
- [x] Expense Service test case
- [x] Expense controller test case
- [x] Tag model redesign
- [x] Add tag
- [x] Delete tag from a entity
- [x] Update tag
- [x] Delete tag
- [x] Associate tag
- [x] Fetch entities for a tag
- [x] Remove association of a tag with all entities
- [x] Tag dao test case
- [x] Tag service test case
- [x] Tag controller test case
- [x] empty condition for all
- [x] test case for above
- [x] todo validation test case
- [x] add validation for percent completion
- [x] final refactor validation
- [ ] remove mandation on description
- [ ] Please refactor test cases!
- [x] message queue 1
- [x] message queue 2
 - [x] message queue 3
- [x] message queue 4
